- name: Creating proxy container folders
  file:
    recurse: yes
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_proxy_dir }}/logs"
    - "{{ nginx_proxy_dir }}/etc_nginx"
    - "{{ nginx_proxy_dir }}/etc_nginx/htpasswd/"
    - "{{ nginx_proxy_dir }}/etc_nginx/user_conf.d"
    - "{{ nginx_proxy_dir }}/build/configs"
    - "{{ nginx_proxy_dir }}/build/scripts"

- name: Copying nginx configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_proxy_dir }}/build/configs"
  with_items:
    - "configs/nginx.conf"
    - "configs/redirector.conf"
    - "configs/ssl_params"

- name: Copying nginx startup scripts
  copy:
    src: "scripts/run_local_ca.sh"
    dest: "{{ nginx_proxy_dir }}/build/scripts"

- name: Rendering proxy build template
  template:
    src: "Docker/Dockerfile.j2"
    dest: "{{ nginx_proxy_dir }}/build/Dockerfile"

- name: Rendering proxy docker-compose template
  template:
    src: "Docker/docker-compose.yaml.j2"
    dest: "{{ nginx_proxy_dir }}/docker-compose.yaml"

- name: Rendering nginx virtual hosts configs
  template:
    src: "{{ item }}"
    dest: "{{ nginx_proxy_dir }}/etc_nginx/user_conf.d/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/vhost_configs/vhost-*.j2

- name: Generating htpasswd for arangodb vhost
  htpasswd:
    path: "{{ nginx_proxy_dir }}/etc_nginx/htpasswd/{{ arangodb_container_name }}.{{ system_hostname }}"
    name: "{{ arangodb_web_user }}"
    password: "{{ arangodb_web_password }}"
    crypt_scheme: md5_crypt

- name: Generating htpasswd for kafka-ui vhost
  htpasswd:
    path: "{{ nginx_proxy_dir }}/etc_nginx/htpasswd/{{ kafka_ui_container_name }}.{{ system_hostname }}"
    name: "{{ kafka_ui_webuser }}"
    password: "{{ kafka_ui_web_password }}"
    crypt_scheme: md5_crypt


- name: Restarting proxy service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ nginx_proxy_dir }}"

