- name: make sure destination directory exists
  file:
    recurse: yes
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ dapp_root_dir }}/statsd/'
  
- name: upload files to build
  synchronize:
    src='files/'
    dest='{{ dapp_root_dir }}/statsd'

- name: upload config compose dir
  synchronize:
    src='files/'
    dest='{{ dapp_root_dir }}/statsd/'

- name: templates for compose
  template:
    src: "{{ item }}"
    dest: "{{ dapp_root_dir }}/statsd/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/*.j2

- name: env template
  template:
    src: '.env.j2'
    dest: '{{ dapp_root_dir }}/statsd/.env'

- name: restart service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ dapp_root_dir }}/statsd"
