- name: Make sure destination directory exists
  file:
    recurse: yes
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kafka_dir }}/files/kafka-connect-arangodb"
    - "{{ kafka_dir }}/build_check/connectors"

- name: Set alias hostname for kafka at 127.0.0.1
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1 kafka'
    line: 127.0.0.1 kafka

- name: Upload files ( build_check )
  synchronize:
    src='files/build_check/'
    dest='{{ kafka_dir }}/build_check'

- name: Upload files ( kafka-connect )
  synchronize:
    src='files/kafka-connect-arangodb/'
    dest='{{ kafka_dir }}/files/kafka-connect-arangodb/'

- name: Render kafka connectors templates
  template:
    src: "{{ item }}"
    dest: "{{ kafka_dir }}/build_check/connectors/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/connectors/*.j2

- name: Render kafka docker-compose template
  template:
    src: 'Docker/docker-compose-{{ kafka_mode }}.yaml.j2'
    dest: '{{ kafka_dir }}/docker-compose.yaml'

- name: Render init-kafka entrypoint template
  template:
    src: 'init-kafka/entrypoint.sh.j2'
    dest: '{{ kafka_dir }}/build_check/entrypoint.sh'
    mode: 0750

- name: Render kafka KRaft init template
  template:
    src: 'kafka-enable-kraft/enable-kraft.sh.j2'
    dest: '{{ kafka_dir }}/files/enable-kraft.sh'
    mode: 0755
  when: kafka_mode == "kraft"
      
- name: Set permissions
  file:
    path: '{{ item }}'
    state: file
    mode: u+rx,g+rx,o-rwx
  loop:
    - '{{ kafka_dir }}/build_check/check.sh'
    - '{{ kafka_dir }}/build_check/entrypoint.sh'

- name: Restart kafka service 
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ dapp_root_dir }}/kafka"

