---
- name: install prerequisites for Docker repository
  dnf:
    name:
      - jq
      - python3-libselinux
      - python3
      - python3-pip
    state: latest

- name: Install epel-release package in oracle
  dnf: 
    name: 
      - oracle-epel-release-el8
    state: latest
  when: ansible_facts['distribution'] == "OracleLinux"

- name: add docker repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: install docker and it's dependencies
  dnf:
    name:
      - "docker-ce-{{ docker_version }}"
    state: present
    update_cache: yes
  register: install_state
  retries: 10
  delay: 10
  until: install_state.rc == 0
  
- name: reload docker service
  service:
    name: docker
    enabled: yes
    state: restarted

- name: Install system packages
  dnf:
    name:
      - vim
      - mc
      - htop
      - rsyslog
      - wget
      - gnupg
      - ca-certificates
      - curl
      - bind-utils
      - gperftools 
      - gperftools-devel
      - gnupg2
      - git
      - rsync
    state: latest

- block:
    - name: Install chrony package
      dnf:
        name: chrony
        state: latest

    - name: Copy the chrony.conf file
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
  when: ntp_enabled is defined and ntp_enabled|bool

- name: Disable SELinux at next reboot
  selinux:
    state: disabled
