---
- name: upgrade pip
  pip:
    name:
      - pip
    state: latest
  vars:
    ansible_python_interpreter: python3

- name: Include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yaml"
