---
- name: Installing yum-utils and stuff
  yum:
    name:
      - yum-utils
      - curl
      - jq
      - python3
      - python3-pip
      - mc
      - git
      - device-mapper-persistent-data
    state: latest
  vars:
    ansible_python_interpreter: python2


