- name: Make sure destination directory exists
  file:
    recurse: yes
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ q_server_dir }}/build/"

- name: Clone a github repository
  git:
    repo: https://github.com/tonlabs/ton-q-server
    dest: "{{ q_server_dir }}/build/ton-q-server"
    clone: yes
    update: yes
    version: master

- name: Updating q-server submodules
  shell: |
    set -euo pipefail
    git submodule init
    git submodule update --recursive
    git submodule foreach 'git submodule init'
    git submodule foreach 'git submodule update  --recursive'
  args:
    executable: "/bin/bash"
    chdir: "{{ q_server_dir }}/build/ton-q-server"

- name: Upload files to build
  synchronize:
    src='files/'
    dest='{{ dapp_root_dir }}/q-server/build'

- name: Rendering q-server docker-compose template
  template:
    src: "Docker/docker-compose.yaml.j2"
    dest: "{{ q_server_dir }}/docker-compose.yaml"

- name: Rendering ENV template
  template:
    src:  ".env.j2"
    dest: "{{ q_server_dir }}/.env"

- name: Rendering q-server docker build template
  template:
    src: "Docker/Dockerfile.j2"
    dest: "{{ q_server_dir }}/build/Dockerfile"

- name: Restart q-server service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ q_server_dir }}"
