- name: Install system packages
  dnf:
    name:
      - "@Development tools"
      - openssl-devel
      - clang
      - cmake
    state: latest

- name: Install system packages
  dnf:
    name:
      - libzstd-devel
    state: absent

