- name: make sure destination directory exists
  file:
    recurse: yes
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ dapp_dir }}/web-root'

- name: upload files
  synchronize:
    src='files/'
    dest='{{ dapp_dir }}/web-root/'

- name: templates for compose
  template:
    src: "{{ item }}"
    dest: "{{ dapp_dir }}/web-root/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/*.j2

- name: restart service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ dapp_dir }}/web-root"
