---
- name: Ensure old versions of Docker are not installed.
  apt:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

- name: non-astra block
  block:
    - name: Add Docker apt key.
      apt_key:
        url: "{{ docker_apt_gpg_key }}"
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present
      register: add_repository_key
      ignore_errors: "{{ docker_apt_ignore_key_error }}"

    - name: Add Docker apt key (alternative for older systems without SNI).
      shell: |
        set -o pipefail
        curl -sSL {{ docker_apt_gpg_key }} | apt-key add -
      args:
        warn: false
        executable: /bin/bash
      when: add_repository_key.failed

    - name: Remove previosly created docker repo list
      file:
        state: absent
        path: /etc/apt/sources.list.d/docker.list

    - name: Add Docker repository.
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        filename: docker
        state: present
        update_cache: true

    - name: Set proper pkg version for ubuntu
      set_fact:
        docker_debuntu_full_package_version: "{{ docker_ubuntu_full_package_version }}"
        docker_compose_plugin_version_deubuntu: "{{ docker_compose_plugin_version_ubuntu }}"
      when: ansible_distribution | lower == "ubuntu"

    - name: Set proper pkg version for debian
      set_fact:
        docker_debuntu_full_package_version: "{{ docker_debian_full_package_version }}"
        docker_compose_plugin_version_deubuntu: "{{ docker_compose_plugin_version_debian }}"
      when: ansible_distribution | lower == "debian"

    - name: Install Docker
      apt:
        name:
          - docker-ce={{ docker_debuntu_full_package_version }}
          - docker-ce-cli={{ docker_debuntu_full_package_version }}
          - docker-ce-rootless-extras={{ docker_debuntu_full_package_version }}
          - containerd.io={{ containerd_deb_version }}
          - docker-compose-plugin={{ docker_compose_plugin_version_deubuntu }}
        state: present
      when:
        - not ansible_distribution_major_version == "9"

    - name: Install Docker on Debian 9
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      when:
        - ansible_distribution_major_version == "9"
  when: ansible_distribution != "Astra Linux"

- name: Install Docker.
  apt:
    name:
      - docker.io
    state: present
    install_recommends: no
  when: ansible_distribution == "Astra Linux"
