---
- name: Removing default rhel podman packages
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
    state: absent

- name: Installing prerequisites for Docker repository
  dnf:
    name:
      - jq
      - python3-libselinux
      - python3
      - python3-pip
    state: latest

- name: add docker repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce-stable
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Installing docker and it dependencies
  dnf:
    name:
      - "docker-ce-{{ docker_version }}"
      - "docker-ce-cli-{{ docker_version }}"
      - "docker-ce-rootless-extras-{{ docker_version }}"
      - "containerd.io-{{ containerd_yum_version }}"
      - "docker-compose-plugin-{{ docker_compose_plugin_version }}"
    state: present
    update_cache: yes
  register: install_state
  retries: 10
  delay: 10
  until: install_state.rc == 0

