---
- name: Remove default rhel podman packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - docker-buildx-plugin
      - podman
    state: absent
  vars:
    ansible_python_interpreter: python2

- name: Delete old docker repo
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: absent

- name: Add docker repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install docker and dependencies
  yum:
    name:
      - "docker-ce-{{ docker_version }}"
      - "docker-ce-cli-{{ docker_version }}"
      - "docker-ce-rootless-extras-{{ docker_version }}"
      - "containerd.io-{{ containerd_yum_version }}"
    state: present
    update_cache: yes

- name: reload docker service
  service:
    name: docker
    enabled: yes
    state: restarted
