
- name: installing yum-utils and stuff
  yum:
    name:
      - yum-utils
      - curl
      - jq
      - python3
      - python3-pip
    state: latest
  vars:
    ansible_python_interpreter: python2

- name: add docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: installing docker packages
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
  vars:
    ansible_python_interpreter: python2
  
  
- name: reload docker service
  service:
    name: docker
    enabled: yes
    state: restarted
