- name: make sure destination directory exists
  file:
    recurse: yes
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ dapp_dir }}/arangodb/build/arango/initdb.d'

- name: upload files
  synchronize:
    src='files/'
    dest='{{ dapp_dir }}/arangodb/'

- name: templates for compose
  template:
    src: "{{ item }}"
    dest: "{{ dapp_dir }}/arangodb/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/*.j2

- name: env template
  template:
    src: '.env.j2'
    dest: '{{ dapp_dir }}/arangodb/.env'

- name: templates for build
  template:
    src: "{{ item }}"
    dest: "{{ dapp_dir }}/arangodb/build/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/build/*.j2

- name: templates for build/arango
  template:
    src: "{{ item }}"
    dest: "{{ dapp_dir }}/arangodb/build/arango/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/arango/*.j2

- name: restart service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ dapp_dir }}/arangodb"
