- name: Making arangodb folder
  file:
    recurse: yes
    path: "{{ arangodb_dir }}/build/arango/initdb.d"
    state: directory

- name: Rendering arangodb init script
  template:
    src: "build/upgrade-arango-db.js.j2"
    dest: "{{ arangodb_dir }}/build/arango/initdb.d/upgrade-arango-db.js"

- name: Rendering arangodb build template
  template:
    src: "Docker/Dockerfile.j2"
    dest: "{{ arangodb_dir }}/build/Dockerfile"

- name: Rendering some configs to build arangodb
  template:
    src: "{{ item }}"
    dest: "{{ arangodb_dir }}/build/arango/{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob:
    - ../templates/arango/*.j2

- name: Rendering arangodb docker-compose template
  template:
    src: "Docker/docker-compose.yaml.j2"
    dest: "{{ arangodb_dir }}/docker-compose.yaml"

- name: Rendering arangodb configs for docker-compose template
  template:
    src: "arango-config.j2"
    dest: "{{ arangodb_dir }}/arango-config"

- name: Rendering environment template
  template:
    src: ".env.j2"
    dest: "{{ arangodb_dir }}/.env"

- name: Restarting arangodb container service
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ arangodb_dir }}"
